- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 12hrs
    TRAINER: Surya
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

