- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item.name }}" # no gap"{{ }}"
        state: "{{ item.state }}" 
      loop:
      - { name: 'git', state: 'present'}
      - { name: 'mysql', state: 'absent'}
      - { name: 'git', state: 'present'}
      - { name: 'zip', state: 'absent'}