- name: filters
  hosts: local
  connection: local
  tasks:
    - name: handle undefine variables
      ansible.builtin.debug:
       msg : "hello {{ person | default('surya') }}"

    - name: convert string to list
      vars:
        fruits: "apple,bananas,orange" #string
      ansible.builtin.debug:
        msg: "Fruits are: {{ fruits | split(',') }}"

    - name: convert map into list
      vars:
        course:
          name: ansible
          duration: 220hrs
          trainer: sivakumar
      ansible.builtin.debug:
        msg: "course information: {{ course | dict2items }} "

    - name: Convert list into map
      vars:
        course:
          - {'key': 'name', 'value': 'ansible'}
          - {'key': 'duration', 'value': '10hrs'}
          - {'key': 'trainer', 'value': 'sivakumar'}
      ansible.builtin.debug:
        msg: "Course information: {{ course | items2dict }} " 

    - name: convert upper to lower
      vars:
        name: SURYA TEJA
      ansible.builtin.debug:
       msg : "hello {{ name | lower }}"  

    - name: convert lower to upper
      vars:
        name: surya teja
      ansible.builtin.debug:
       msg : "hello {{ name | upper }}"  