- name: install and run nginx
  hosts: all
  become: yes # -b = sudo access
  serial: 2
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    tags:
    - run
    ansible.builtin.service:
      name: nginx
      state: started